### ISSUE TITLE
Copilot only triggers when I save my file

### ISSUE THREAD

**Issue by AlexandreSajus** [thanhnew2001/vsc-taipy#1]
Copilot will only send prompt when I save the file

Nothing happens here after I typed:
![image](https://github.com/thanhnew2001/vsc-taipy/assets/62465003/68e981a6-17a1-4a6a-a3c4-c78a97956e88)

When I save:
![image](https://github.com/thanhnew2001/vsc-taipy/assets/62465003/6b883be9-57c1-4840-9e95-8ec6f6945541)

**Comment by thanhnew2001** [comment]
Will check but it seems related to the version of VS. My version is 1.84.0

<img width="574" alt="image" src="https://github.com/thanhnew2001/vsc-taipy/assets/3261272/181cc4b5-c9f3-44e2-b418-31d66bd4cddf">

**Comment by AlexandreSajus** [comment]
Let's try with the new version of Taipy Copilot where you fixed the bugs, I'll try and I'll specify the VSCode version

**Comment by AlexandreSajus** [comment]
The issue does not get triggered if you have autosave enabled in VSCode

**Comment by thanhnew2001** [comment]
should be close as auto-save will be enabled when installing TC
