### ISSUE TITLE
Taipy Copilot blocks the use of the tab key for other extensions

### ISSUE THREAD

**Issue by AlexandreSajus** [thanhnew2001/vsc-taipy#11]
When Taipy Copilot is enabled, the tab key can only create space or write a Taipy completion. When another code completion tool like Codium, Copilot or Pylance is used, pressing tab does not write the completion but creates a space instead.

Taipy Copilot should only use the tab key when a Taipy Copilot suggestion has been generated and the user has not moved yet

**Comment by thanhnew2001** [comment]
Fixed in release 1.0.9+

**Comment by AlexandreSajus** [comment]
Not fixed, pressing tab here will create a space instead of completion. Critical issue
![image](https://github.com/thanhnew2001/vsc-taipy/assets/62465003/b6253063-07bb-496e-a10a-748b49ce02ed)

**Comment by thanhnew2001** [comment]
fixed in 1.0.12
