### ISSUE TITLE
When two completion tools have a suggestion

### ISSUE THREAD

**Issue by AlexandreSajus** [thanhnew2001/vsc-taipy#12]
Maybe a non-issue but this is what happens when you use both Copilot and Taipy Copilot, you get two suggestions stacked
![image](https://github.com/thanhnew2001/vsc-taipy/assets/62465003/947e603a-c0d2-4120-85f7-caa6b9ba217e)

**Comment by thanhnew2001** [comment]
TC has a enabled button so it should be convenient for users to stop it.
