### ISSUE TITLE
Non existent property sort for table

### ISSUE THREAD

**Issue by AlexandreSajus** [thanhnew2001/vsc-taipy#16]
Asking to display a sorted table results in:
![image](https://github.com/thanhnew2001/vsc-taipy/assets/62465003/1c44cf04-3af1-4dca-8f04-85ef75d49f77)

sort does not exist, Taipy Copilot should sort sales using pandas like sales.sort_values(by=["x"])

**Comment by thanhnew2001** [comment]
False training samples have been removed
