### ISSUE TITLE
Slider list of values fails

### ISSUE THREAD

**Issue by AlexandreSajus** [thanhnew2001/vsc-taipy#17]
This failed
![image](https://github.com/thanhnew2001/vsc-taipy/assets/62465003/273c8eb8-0f59-4503-8c3c-dccaee4f4fa2)

The correct property is "lov=10;20;30" 

This is part of a larger issue where Taipy Copilot seems to often hallucinate properties if we don't give him the exact names of properties in the prompt. It might get solved by adding training prompts that don't contain the exact names of properties but instead a more natural language

**Comment by thanhnew2001** [comment]
training samples for this particular cases are included
