### ISSUE TITLE
"Please give me few more initial..." warning

### ISSUE THREAD

**Issue by AlexandreSajus** [thanhnew2001/vsc-taipy#18]
What does this warning mean:
![image](https://github.com/thanhnew2001/vsc-taipy/assets/62465003/3604d852-5abc-4b72-8da6-04276a17b19d)

How does the user work around this

**Comment by thanhnew2001** [comment]
Sometime a non-sense prompt was typed, I am not sure what is the right message to inform users so that they can change the prompt

**Comment by AlexandreSajus** [comment]
I could not really get out of this situation even by changing the prompt. We can investigate more. Maybe in the meantime, change the message to "Failed to generate, try changing your prompt"

**Comment by thanhnew2001** [comment]
Replace message by Failed to generate, try changing your prompt 
Deployed in 1.0.13
