### ISSUE TITLE
Text present after cursor warning is wrong

### ISSUE THREAD

**Issue by AlexandreSajus** [thanhnew2001/vsc-taipy#2]
The TaiPycopilot stopped as there is text present after cursor is wrong. Also Copilot should be able to generate code regardless of if there is text after:
![image](https://github.com/thanhnew2001/vsc-taipy/assets/62465003/ff3a51df-fe2b-48f1-ac12-c8f32b78a395)

**Comment by thanhnew2001** [comment]
Fixed it
