### ISSUE TITLE
Wrong code generated on simple examples (I'll add new examples here)

### ISSUE THREAD

**Issue by AlexandreSajus** [thanhnew2001/vsc-taipy#5]
![image](https://github.com/thanhnew2001/vsc-taipy/assets/62465003/88bc5895-ebcd-4523-bd80-40420c44294a)

**Comment by thanhnew2001** [comment]
<img width="529" alt="image" src="https://github.com/thanhnew2001/vsc-taipy/assets/3261272/f4308d3e-28c9-4c3c-b463-b0b905801341">

**Comment by thanhnew2001** [comment]
The new model is able to do all these simple prompts
