### ISSUE TITLE
Change status bar informations

### ISSUE THREAD

**Issue by AlexandreSajus** [thanhnew2001/vsc-taipy#9]
Replace the informations displayed here:
![image](https://github.com/thanhnew2001/vsc-taipy/assets/62465003/5617dce1-cdab-4f3f-a786-1f16c65ea6b8)

with: `Taipy Copilot: Enabled`

Remove `Mode: Taipy Markdown` and default to Taipy Markdown

And keep the status information like `Sending to API`

**Comment by thanhnew2001** [comment]
It has been fixed with the 1>.0.9
